version: '3'

volumes:
  db-data: {}

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    volumes:
      - .:/auth_server
      - ~/.aws:/root/.aws
    ports:
      - "3000:3000"
    depends_on:
      - db